version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: tpu-db-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'tpu-db-1'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./setup:/docker-entrypoint-initdb.d
      - ./backup:/backup

  postgres-postgis:
    image: kartoza/postgis:15-3
    container_name: tpu-db-postgres-postgis
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgis-data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
    volumes:
      - ./data-mongo:/data/db

  mongo-express:
    image: mongo-express:1.0.0
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd
      ME_CONFIG_MONGODB_URL: mongodb://root:pwd@mongo:27017/